/**
 * Tells the reader an article was written by software.
 *
 * Not optional decoration. The moment autonomous publishing is switched on,
 * the site is publishing unreviewed machine-written copy under a masthead, and
 * a reader has no way to tell that apart from reported journalism. Saying so is
 * the minimum that keeps the editorial standards page true — and Google's
 * guidance on AI content is about disclosure and usefulness, not a ban, so
 * concealing it carries risk without buying anything.
 *
 * Rendered from the article's own ai_assisted flag, so it cannot fall out of
 * step with what actually produced the piece.
 */
export function AiDisclosure({
  reviewed,
  unverifiedCount,
}: {
  reviewed: boolean;
  unverifiedCount: number;
}) {
  return (
    <aside className="mt-8 border-l-2 border-hairline pl-4">
      <p className="text-meta font-semibold text-ink">
        This article was written using AI
      </p>
      <p className="mt-1 max-w-measure text-meta leading-relaxed text-muted">
        {reviewed
          ? "It was drafted by a language model and reviewed by an editor before publication."
          : "It was generated by a language model and published automatically, without being read by an editor first."}
        {unverifiedCount > 0
          ? ` The model reported ${unverifiedCount} statement${unverifiedCount === 1 ? "" : "s"} in it that it could not verify.`
          : ""}
      </p>
    </aside>
  );
}
