import { createClient } from "@/lib/supabase/server";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";
const PUBLICATION_NAME = "Newswebsite";
const PUBLICATION_LANGUAGE = "en";

/**
 * Google News sitemap.
 *
 * Separate from the main sitemap because it needs the news namespace and,
 * critically, a two-day window: Google News ignores anything older, and a news
 * sitemap listing a thousand stale URLs is treated as a quality signal against
 * you rather than a bigger index.
 *
 * Hand-built rather than generated by next/sitemap, which has no news
 * namespace support.
 */
export const revalidate = 300;

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

export async function GET() {
  const supabase = await createClient();
  const twoDaysAgo = new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString();

  const { data } = await supabase
    .from("articles")
    .select("slug, headline, published_at, categories!inner ( slug )")
    .in("status", ["published", "scheduled"])
    .lte("published_at", new Date().toISOString())
    .gte("published_at", twoDaysAgo)
    .order("published_at", { ascending: false })
    .limit(1000);

  const entries = (data ?? [])
    .map((article) => {
      const categorySlug = (article.categories as unknown as { slug: string }).slug;
      const url = `${SITE_URL}/${categorySlug}/${article.slug}`;
      return `  <url>
    <loc>${escapeXml(url)}</loc>
    <news:news>
      <news:publication>
        <news:name>${escapeXml(PUBLICATION_NAME)}</news:name>
        <news:language>${PUBLICATION_LANGUAGE}</news:language>
      </news:publication>
      <news:publication_date>${article.published_at}</news:publication_date>
      <news:title>${escapeXml(article.headline)}</news:title>
    </news:news>
  </url>`;
    })
    .join("\n");

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:news="http://www.google.com/schemas/sitemap-news/0.9">
${entries}
</urlset>`;

  return new Response(xml, {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
      "Cache-Control": "public, max-age=300, s-maxage=300",
    },
  });
}
